### ISSUE TITLE
Problem connecting GCM with TLS connection

### ISSUE THREAD

**Issue by mezerny** [adhearsion/blather#125]
I'm trying to establish XMPP communication with Google Cloud Messaging server with Blather but currently I cant even establish TLS connection.

I'm able to connect to Google Talk and send a message to another Google talk account and recieve the reply, but when I change the arguments for GCM server connection when_ready handler doesn't work at all.

What I'm trying to do is (working example):

```ruby
require 'rubygems'
require 'blather/client'

setup 'my_email@gmail.com', 'my_password'

when_ready do
  say 'my_another_email@gmail.com', 'Hi, User!'
end

message :chat?, :body do |m|
  say m.from, "You sent: #{m.body}"
end
```

But when I change the setup method to the following, 'when_ready' method is never called, application just finishes the work with exit code 0:

```ruby
setup 'my_project_id@gcm.googleapis.com', 'my_gcm_project_api_key', 'gcm.googleapis.com', 5235, './certs'

when_ready do
   say 'my_project_id@gcm.googleapis.com', 'Hi GCM'
end
```

When I start it in debug mode I can see following in console:

```
D, [2013-11-25T09:33:27.013499 #14148] DEBUG -- : USING JID: my_project_id@gcm.googleapis.com
D, [2013-11-25T09:33:27.083506 #14148] DEBUG -- : SENDING: (D:/bin/Ruby200/lib/ruby/gems/2.0.0/gems/blather-0.8.8/lib/blather/stream/client.rb:12:in `start') <stream:stream to='gcm.googleapis.com' xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>
```

After that application stops.

Could you please give me any advice about what I'm doing wrong? Possibly, the problem is in TLS connection establishing?

**Comment by techhelper1** [comment]
Will there be a commit to fix for this?

**Comment by benlangfeld** [comment]
This is not something broken in Blather, but rather the server not supporting the current XMPP specifications. I'm going to close this ticket for now.

**Comment by KeithP** [comment]
It would be great to have this capability to enable a server to message android and IOS devices via google's Cloud Messaging service (GCM). https://developers.google.com/cloud-messaging/ccs
OR is there a good alternative to be able to both send downstream messages and listen for upstream messages via GCM? 
Perhaps a workaround ? or can you reopen this in the light of proposed standard dated June 2015: https://tools.ietf.org/html/rfc7590
Thanks!
