### ISSUE TITLE
No threads Please!

### ISSUE THREAD

**Issue by artyomb** [adhearsion/blather#130]
Please remove that GirlFriday dependancies and make the lib single thread. There could be optional pooling policy if someon required.
https://github.com/adhearsion/blather/blob/develop/lib/blather/client/client.rb#L62

``` ruby
Blather::Client::initialize
...
#- @handler_queue = GirlFriday::WorkQueue.new :handle_stanza, :size => 5 do |stanza|
#-        handle_data stanza
#-      end
@handler_queue = EM::Queue.new
@handler_queue.pop(cb=proc{ |stanza|
        handles stanza
        @handler_queue.pop cb
})
...
```

**Comment by singpolyma** [comment]
Indeed.  GirlFriday is *not* compatible with EventMachine and causes the reactor to get stuck!

**Comment by benlangfeld** [comment]
PRs accepted.

**Comment by singpolyma** [comment]
@benlangfeld sure.  I'm curious: what's the rationale behind having something like GirlFriday in here to begin with?  Now that I've discovered this is causing the stalling in my app, I can work around it by passing `workqueue_count: 0`, but I'm curious what the goal of setting the workqueue size to > 0 would be?

**Comment by benlangfeld** [comment]
Simply poor design choices in [Punchblock](https://github.com/adhearsion/punchblock) leading to the equally poor choice to rely on pooling to "avoid deadlocks".
