### ISSUE TITLE
Blather as client for testing purposes

### ISSUE THREAD

**Issue by brbrr** [adhearsion/blather#152]
Hi,
I'm looking for a way to use blather as xmpp client (which is using some custom extensions like OTP's) for testing (automation) purposes. So basically I want to have instance which could login/register/send messages/be extendable(in meaning of custom requests)

```
cli = CustomBlather.new(@jid)
cli.register
cli.login
cli.message_to(@friend_jid, 'Hi there')
cli.update_cert
```

Is it possible to build such client with blather? Thanks alot in advance!

**Comment by benlangfeld** [comment]
Yes. If you have a specific usage question, please take it to the mailing list. If you have a suspected bug, please post it here.

**Comment by brbrr** [comment]
Ok, sorry for this issue. by Mailing list I suppose you mean google groups.
